### ISSUE TITLE
fail on 'npm install' on Mac

### ISSUE THREAD

**Issue by joemontibello** [montanaflynn/Spellcheck-API#2]
Couldn't get this to install on my Mac (OS X 10.11.4).

Here's what I saw. I'm also attaching a log file that npm suggested I include.

I'm not experienced with node so I would not be shocked to hear that I'm doing something wrong there.

Take care,
Joe M.
=-==-=-=-=-=-=-=-=-=-=-=-=-=-=
## npm install

> spellchecker@1.1.0 install /Users/dltg/Spellcheck-API/node_modules/spellchecker
> node-gyp rebuild

  CXX(target) Release/obj.target/spellchecker/src/main.o
In file included from ../src/main.cc:3:
../node_modules/nan/nan.h:260:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:255:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:660:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:671:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/node_buffer.h:31:40: note: candidate
      function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/dltg/.node-gyp/4.4.1/include/node/node_buffer.h:43:40: note: candidate
      function not viable: 2nd argument ('const char _') would lose const
      qualifier
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/dltg/.node-gyp/4.4.1/include/node/node_buffer.h:28:40: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/dltg/.node-gyp/4.4.1/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../src/main.cc:3:
../node_modules/nan/nan.h:675:12: error: no viable conversion from returned value
      of type 'v8::MaybeLocalv8::Object' to function return type
      'v8::Localv8::Object'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:210:7: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocalv8::Object' to 'const v8::Localv8::Object &' for 1st
      argument
class Local {
      ^
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:210:7: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object &&' for 1st argument
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:214:13: note: candidate template
      ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:326:13: note: candidate template
      ignored: could not match 'S _' against 'v8::MaybeLocalv8::Object'
  V8_INLINE Local(S_ that)
            ^
In file included from ../src/main.cc:3:
../node_modules/nan/nan.h:682:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/main.cc:3:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/dltg/.node-gyp/4.4.1/include/node/node.h:42:
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    _(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:413:12: note: in instantiation of function template
      specialization 'v8::Localv8::Primitive::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/main.cc:3:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/dltg/.node-gyp/4.4.1/include/node/node.h:42:
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:423:12: note: in instantiation of function template
      specialization 'v8::Localv8::Boolean::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/main.cc:3:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/dltg/.node-gyp/4.4.1/include/node/node.h:42:
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:221:5: error: assigning to
      'v8::Function _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1513:12: note: in instantiation of function template
      specialization 'v8::Localv8::Function::Localv8::Value' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/main.cc:3:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/dltg/.node-gyp/4.4.1/include/node/node.h:42:
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:221:5: error: assigning to
      'v8::Object _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dltg/.node-gyp/4.4.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1631:12: note: in instantiation of function template
      specialization 'v8::Localv8::Object::Localv8::Value' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).Asv8::Object());
           ^
../node_modules/nan/nan.h:397:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

9 errors generated.
make: **\* [Release/obj.target/spellchecker/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dltg/Spellcheck-API/node_modules/spellchecker
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dltg/Spellcheck-API/npm-debug.log

[npm-debug-log.pdf](https://github.com/montanaflynn/Spellcheck-API/files/189658/npm-debug-log.pdf)

**Comment by datsabk** [comment]
+1 on Linux as well

**Comment by montanaflynn** [comment]
Here's the dependencies github repo: https://github.com/atom/node-spellchecker
